CREATE TABLE device (
  id SERIAL NOT NULL PRIMARY KEY
);

CREATE TABLE sensor (
  id SERIAL NOT NULL PRIMARY KEY,
  device_id INTEGER NOT NULL REFERENCES device(id)
);

CREATE TABLE unit (
  id SERIAL NOT NULL PRIMARY KEY,
  type VARCHAR(50) NOT NULL
);

CREATE TABLE sensor_data (
  sensor_id INTEGER NOT NULL REFERENCES sensor(id),
  unit_id INTEGER NOT NULL REFERENCES unit(id),
  value VARCHAR(100) NOT NULL,
  timestmp TIMESTAMPTZ NOT NULL
);